### ISSUE TITLE
path not working

### ISSUE THREAD

**Issue by kofifus** [serilog/serilog-sinks-file#133]
I may be messing something obvious but since latest update I can't get paths in filenames to work.

This
```
     Log.Logger = new LoggerConfiguration().WriteTo.File(
          @"DashboardServer.log", 
          fileSizeLimitBytes: 100 * 1024 * 1024, 
          flushToDiskInterval: TimeSpan.FromMilliseconds(300),
          rollOnFileSizeLimit: true
        ).CreateLogger();
```

works

but this
```
     Log.Logger = new LoggerConfiguration().WriteTo.File(
          @"\DashboardServer.log", 
          fileSizeLimitBytes: 100 * 1024 * 1024, 
          flushToDiskInterval: TimeSpan.FromMilliseconds(300),
          rollOnFileSizeLimit: true
        ).CreateLogger();
```

does not generate the file or log or throws any error.

(using latest asp.net core preview, Serolog.AspNetCore v3.2.1-dev-00142, Serilog.Sinks.File 5.0.0-dev-00864)

What's going on ?
Thanks

**Comment by cocowalla** [comment]
Is this on Windows? If so, I'd recommend to use a relative path (as in the your first example), or an absolute path.

On Windows, I don't think your second example has a well defined meaning.

**Comment by kofifus** [comment]
thanks @cocowalla , yes windows, using "\DashboardServer.log" is well defined in asp.net - it is the root of the drive where the server is running from. But anyway - @"c:\DashboardServer.log" also does not work. Also not having any errors is very confusing !

**Comment by cocowalla** [comment]
Hmm, the absolute path example you gave should work. Can you try this before you do anything with serilog? 
`Serilog.Debugging.SelfLog.Enable(msg => Debug.WriteLine(msg));`

That will write internal serilog diags to Debug (you can replace with `Console.WriteLine` if you prefer).

**Comment by kofifus** [comment]
Thanks ! that shows:

```
2020-02-14T08:14:26.2359623Z Caught exception while emitting to sink Serilog.Sinks.File.PeriodicFlushToDiskSink: System.UnauthorizedAccessException: Access to the path 'c:\DashboardServer.log' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Serilog.Sinks.File.FileSink..ctor(String path, ITextFormatter textFormatter, Nullable`1 fileSizeLimitBytes, Encoding encoding, Boolean buffered, FileLifecycleHooks hooks)
   at Serilog.Sinks.File.RollingFileSink.OpenFile(DateTime now, Nullable`1 minSequence)
   at Serilog.Sinks.File.RollingFileSink.AlignCurrentFileTo(DateTime now, Boolean nextSequence)
   at Serilog.Sinks.File.RollingFileSink.Emit(LogEvent logEvent)
   at Serilog.Sinks.File.PeriodicFlushToDiskSink.Emit(LogEvent logEvent)
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)
```

**Comment by cocowalla** [comment]
Ah, great, then it shows the problem: the process doesn't have permission to write to the specified path.

As an aside, on Windows, I generally recommend created a folder for your app in `%PROGRAMDATA%`, making sure your process user has access, and writing logs there.

**Comment by kofifus** [comment]
I dont understand,  there is no reason for asp.net not to have permissions to write to the root of C , also this used to work

Also why is CreateLogger not throwing an exception or notifying of an error on some way ?

**Comment by cocowalla** [comment]
On systems I usually work on, only admins have write access to the root (assuming it's the OS drive).

Regarding exceptions, Serilog has a ["no throw" policy] (https://github.com/serilog/serilog/wiki/Reliability)

**Comment by kofifus** [comment]
OK I had to grant full control to IIS_IUSRS on the path

This was working fine until last week and is still working fine on a C# console app I'm running, something must have changed in either windows update or Serilog or (my guess) ASP.Net Core .. 

Thanks for your help.
