### ISSUE TITLE
How to configure the rollingInterval in app.config

### ISSUE THREAD

**Issue by chucklu** [serilog/serilog-sinks-file#162]
Tried with
```xml
  <add key="serilog:write-to:File.rollingInterval" value="Day" />
```
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at Serilog.Settings.KeyValuePairs.SettingValueConversions.ConvertToType(String value, Type toType)
   at Serilog.Settings.KeyValuePairs.KeyValuePairSettings.ConvertOrLookupByName(String valueOrSwitchName, Type type, IReadOnlyDictionary`2 declaredSwitches)
   at Serilog.Settings.KeyValuePairs.KeyValuePairSettings.<>c__DisplayClass26_0.<ApplyDirectives>b__1(<>f__AnonymousType3`2 <>h__TransparentIdentifier0)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Serilog.Settings.KeyValuePairs.KeyValuePairSettings.ApplyDirectives(List`1 directives, IList`1 configurationMethods, Object loggerConfigMethod, IReadOnlyDictionary`2 declaredSwitches)
   at Serilog.Settings.KeyValuePairs.KeyValuePairSettings.Configure(LoggerConfiguration loggerConfiguration)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
   at Serilog.Configuration.LoggerSettingsConfiguration.KeyValuePairs(IEnumerable`1 settings)
   at Serilog.Settings.AppSettings.AppSettingsSettings.Configure(LoggerConfiguration loggerConfiguration)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
   at Serilog.AppSettingsLoggerConfigurationExtensions.AppSettings(LoggerSettingsConfiguration settingConfiguration, String settingPrefix, String filePath)
   at SerilogTest2.Program.Main(String[] args) in C:\Users\clu\source\repos\SerilogTest\SerilogTest2\Program.cs:line 31

**Comment by chucklu** [comment]
Tried with 
```xml
<add key="serilog:write-to:RollingFile.rollingInterval" value="RollingInterval.Day" />
```
System.ArgumentException: Requested value 'RollingInterval.Day' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Serilog.Settings.KeyValuePairs.SettingValueConversions.ConvertToType(String value, Type toType)
   at Serilog.Settings.KeyValuePairs.KeyValuePairSettings.ConvertOrLookupByName(String valueOrSwitchName, Type type, IReadOnlyDictionary`2 declaredSwitches)
   at Serilog.Settings.KeyValuePairs.KeyValuePairSettings.<>c__DisplayClass26_0.<ApplyDirectives>b__1(<>f__AnonymousType3`2 <>h__TransparentIdentifier0)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Serilog.Settings.KeyValuePairs.KeyValuePairSettings.ApplyDirectives(List`1 directives, IList`1 configurationMethods, Object loggerConfigMethod, IReadOnlyDictionary`2 declaredSwitches)
   at Serilog.Settings.KeyValuePairs.KeyValuePairSettings.Configure(LoggerConfiguration loggerConfiguration)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
   at Serilog.Configuration.LoggerSettingsConfiguration.KeyValuePairs(IEnumerable`1 settings)
   at Serilog.Settings.AppSettings.AppSettingsSettings.Configure(LoggerConfiguration loggerConfiguration)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
   at Serilog.AppSettingsLoggerConfigurationExtensions.AppSettings(LoggerSettingsConfiguration settingConfiguration, String settingPrefix, String filePath)
   at SerilogTest2.Program.Main(String[] args) in C:\Users\clu\source\repos\SerilogTest\SerilogTest2\Program.cs:line 32

**Comment by cocowalla** [comment]
Could you post all of the XML settings you are using relating to Serilog please?

Could you also post the c# logger builder code you are using?

And finally, can you post all Serilog NuGet packages you are using please?

**Comment by chucklu** [comment]
@cocowalla  You might clone this repository, https://github.com/ChuckTest/SerilogTest/tree/app-setting/SerilogTest2
Then switch to branch app-setting, and check the source code of project SerilogTest2

**Comment by cocowalla** [comment]
A repro is even better, thanks! - I'll take another look at this later today.

**Comment by cocowalla** [comment]
I had a look, and the issue isn't the `RollingInterval`, it's the null value for:

```xml
<add key="serilog:write-to:File.retainedFileCountLimit" value="null" />
```

Hope this helps!
Instead, you should use an empty value:

```xml
<add key="serilog:write-to:File.retainedFileCountLimit" value="null" />
```

**Comment by chucklu** [comment]
@cocowalla  Thanks, it works now. And I just read the documentation again, and found recommended configuration
Omitting the value will set the parameter to null:
```xml
    <add key="serilog:write-to:File.fileSizeLimitBytes" />
```

@nblumhardt  Is it possible to throw correct exception? The previous version works fine without  section
```
 <add key="serilog:write-to:File.rollingInterval" value="Day" />
```

**Comment by chucklu** [comment]
I will close this issue now, hope you can give the correct error message next time.
