### ISSUE TITLE
AuditTo + File Sink = IOException "file being used by another process"

### ISSUE THREAD

**Issue by spaasis** [serilog/serilog-sinks-file#330]
The Serilog maintainers want you to have a great experience using Serilog.Sinks.File, and will happily track down and resolve bugs. We all have limited time, though, so please think through all of the factors that might be involved and include as much useful information as possible 😊.

ℹ If the problem is caused by a sink or other extension package, please track down the correct repository for that package and create the report there: this tracker is for the **Serilog.Sinks.File** package only.

**Description**
Hi! I'm attempting to create an audit log to a file, but am running into an issue on application startup:

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: The process cannot access the file '...\src\Presentation\WebApi\Logs\audit.txt' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Serilog.Sinks.File.FileSink..ctor(String path, ITextFormatter textFormatter, Nullable`1 fileSizeLimitBytes, Encoding encoding, Boolean buffered, FileLifecycleHooks hooks)

```

**Reproduction**
My program.cs:

```
builder.Host.UseSerilog((_, services, configuration) => {
    var scope = services.CreateScope();
    configuration
            .Enrich.FromLogContext()
            .ReadFrom.Configuration(config);
});

```

My appsettings:
```
  "Serilog": {
    "WriteTo": [
      {
        "Name": "Logger",
        "Args": {
          "configureLogger": {
            "Filter": [
              {
                "Name": "ByExcluding",
                "Args": {
                  "expression": "Audit = true"
                }
              }
            ],
            "WriteTo": [
              {
                "Name": "Console",
                "Args": {
                  "restrictedToMinimumLevel": "Information",
                  "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Scope} {Message:lj} User: {UserId}{NewLine}{Exception}"
                }
              }
            ]
          }
        }
      }
    ],
    "AuditTo": [
      {
        "Name": "Logger",
        "Args": {
          "configureLogger": {
            "AuditTo": [
              {
                "Name": "File",
                "Args": {
                  "path": "Logs/audit.txt",
                  "restrictedToMinimumLevel": "Information",
                  "outputTemplate": "AUDIT! {Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj} User: {UserId}{NewLine}{Exception}"
                }
              }
            ],
            "Filter": [
              {
                "Name": "ByIncludingOnly",
                "Args": {
                  "expression": "Audit = true"
                }
              }
            ]
          }
        }
      }
    ]
  }, 
```

**Expected behavior**
App starts, events decorated with the attribute are logged to the file and not the console sink.

**Relevant package, tooling and runtime versions**
Dotnet 8
Serilog.Sinks.File 6.0.0
Serilog.Settings.Configuration 8.0.4
Serilog.Expressions 5.0.0

**Additional context**
If I change the configuration to log to Console instead of File, it works. If I change the nested AuditTo to WriteTo, the app starts but nothing is logged to the file. Regular WriteTo -> File works as expected.

I'm sure there's something borked in the appsettings, but I just can't spot it..

**Comment by nblumhardt** [comment]
Hi! The message will most likely be accurate, here. Either an app you're running (IDE, text editor?) or some process on the machine (AV? another instance of the same app?) will be holding an open handle to that file. You might need to use sysinternals tools to track it down, if all else fails.

**Comment by spaasis** [comment]
Hmm, that might be, but using the PowerToys 'File Locksmith' it can't pick any other processes accessing the file.
Anyway, I forgot a key part of the logging infra here, which at least allows me to get the config working.

In the program.cs I'm calling 
```
Log.Logger = new LoggerConfiguration()
    .ReadFrom.Configuration(config)
    .CreateLogger(); //log startup errors
```
And removing this allows the app to start and the audit log to work as expected. Apparently this "create a logger instance just for  the startup code" is no longer necessary, since I seem to get the same log output regardless?

Closing, since this seems to work - full working appsettings here for future visitors:

```
  "Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Information",
        "System": "Warning"
      }
    },
    "WriteTo": [
      {
        "Name": "Logger",
        "Args": {
          "configureLogger": {
            "Filter": [
              {
                "Name": "ByExcluding",
                "Args": {
                  "expression": "Audit = true"
                }
              }
            ],
            "WriteTo": [
              {
                "Name": "File",
                "Args": {
                  "path": "Logs/information.log",
                  "rollingInterval": "Day",
                  "restrictedToMinimumLevel": "Information",
                  "retainedFileCountLimit": 5,
                  "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj} User: {UserId}{NewLine}{Exception}"
                }
              },
              {
                "Name": "Console",
                "Args": {
                  "restrictedToMinimumLevel": "Information",
                  "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj} User: {UserId}{NewLine}{Exception}"
                }
              },
              {
                "Name": "Debug",
                "Args": {
                  "restrictedToMinimumLevel": "Information",
                  "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj} User: {UserId}{NewLine}{Exception}"
                }
              }
            ]
          }
        }
      }
    ],
    "AuditTo": [
      {
        "Name": "Logger",
        "Args": {
          "configureLogger": {
            "Filter": [
              {
                "Name": "ByIncludingOnly",
                "Args": {
                  "expression": "Audit = true"
                }
              }
            ],
            "AuditTo": [
              {
                "Name": "File",
                "Args": {
                  "path": "Logs/audit.log",
                  "restrictedToMinimumLevel": "Information",
                  "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj} User: {UserId}{NewLine}{Exception}"
                }
              }
            ]
          }
        }
      }
    ]
  },
```

**Comment by nblumhardt** [comment]
Ah I see, the missing piece is the clue :+1: -  "another process" from the OS point of view also includes other handles opened in the _current_ process. Check out https://nblumhardt.com/2020/10/bootstrap-logger/ - `CreateBootstrapLogger()` on the first logger configuration should allow your scenario to work.

**Comment by spaasis** [comment]
@nblumhardt Brilliant, that works 🎖️ Thanks a lot!
