### ISSUE TITLE
Cannot clear log because it is being used by another process

### ISSUE THREAD

**Issue by fireundubh** [serilog/serilog-sinks-file#73]
Regression of #19 perhaps?

I'm trying to clear the log file with:

```csharp
public static void Clear()
{
	File.Create(FullPath).Close();
}
```

But I'm getting this exception.

```
System.IO.IOException
  HResult=0x80070020
  Message=The process cannot access the file 'C:\Users\fireundubh\AppData\Local\KingmakerMods.pw\patchwork.log' because it is being used by another process.
  Source=mscorlib
  StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) in f:\dd\ndp\clr\src\BCL\system\io\__error.cs:line 180
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) in f:\dd\ndp\clr\src\BCL\system\io\filestream.cs:line 880
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize) in f:\dd\ndp\clr\src\BCL\system\io\filestream.cs:line 535
   at System.IO.File.Create(String path) in f:\dd\ndp\clr\src\BCL\system\io\file.cs:line 207
   at PatchworkLauncher.LogManager.Clear() in E:\repos\KingmakerMods.pw Launcher\PatchworkLauncher\GUI\LogManager.cs:line 33
   at PatchworkLauncher.LaunchManager..ctor() in E:\repos\KingmakerMods.pw Launcher\PatchworkLauncher\GUI\LaunchManager.cs:line 39
   at PatchworkLauncher.Program.Main() in E:\repos\KingmakerMods.pw Launcher\PatchworkLauncher\Program.cs:line 18
```

I'm calling Clear() after initializing the ILogger.CreateLogger() instance, which locks the file. The workaround is to call Clear() before ILogger initialization, but I wonder if Serilog has a way to clear a log file natively? That said, I'm probably going to use the rolling log system instead, but I thought I'd surface this anyway.

**Comment by nblumhardt** [comment]
Thanks for raising this - sorry we weren't able to get you an answer. I think that if `shared: true` is specified, it may be possible to open and clear a log file that's in use, however I don't think we explicitly designed for this scenario and there could be gotchas. If anyone coming across this in the future is keen to investigate please jump in, but I'll close this for now. Thanks again!
